export const SET_GRAPH_DATA = 'SET_GRAPH_DATA';
export const INITIAL_CONDITION_CHANGED = 'INITIAL_CONDITION_CHANGED';
export const FORWARD_RATE_CHANGED = 'FORWARD_RATE_CHANGED';
export const BACKWARD_RATE_CHANGED = 'BACKWARD_RATE_CHANGED';

export const INIT_SLIDER_VARS_CHANGED = 'INIT_SLIDER_VARS_CHANGED';
export const FORWARD_SLIDER_VARS_CHANGED = 'FORWARD_SLIDER_VARS_CHANGED';
export const BACKWARD_SLIDER_VARS_CHANGED = 'BACKWARD_SLIDER_VARS_CHANGED';

export const CB_NON_ZERO_CHECKED_CHANGED = 'CB_NON_ZERO_CHECKED_CHANGED';

export const SET_SCHEME_TEXT = 'SET_SCHEME_TEXT';

export const SET_GENERAL_MODEL = 'SET_GENERAL_MODEL';

export const TOGGLE_LOG_X = 'TOGGLE_LOG_X';
export const TOGGLE_LOG_Y = 'TOGGLE_LOG_Y';

export const SET_SCHEME_AND_CB_NON_ZERO = 'SET_SCHEME_AND_CB_NON_ZERO';
